### ISSUE TITLE
Registration / Sign in page 

### ISSUE THREAD

**Issue by lcryan** [lcryan/happyhour_application_lr#8]
**Goal** 
User has the possibility to register as a user and create an account (minimal with the p. of saving name, password, email) see 
here : 

https://github.com/hogeschoolnovi/novi-educational-backend-documentation

**Steps to follow:** 

- [x] Set up registration page with name, last name, email, password , repeat password option, save button 
- [x] Error messages, if a. email is invalid (no com, nl etc. no @ etc.) 
- [x] Error messages, if requirements password setup are not met:
- [x] Requirements password: tbd - check with backend as well - how much can be stored??? 
- [x] set up requirements username : error messages: not valid or already exists
- [ ] System stores info in Novi backend 
- [x] **NOTE: research on how backend and frontend work on this part still has to be done.** 

- [x] once user is successfully registered: system navigates him/ her to login page. User follows login procedure to get acces to his account homepage.

**Comment by ScottGuymer** [comment]
For error messages you can lean on the built in html validation for some simple things. ([first example here](https://www.educba.com/html-form-validation/))

**Comment by lcryan** [comment]
Done and solved
